/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddCountryForm: typeof import('./src/components/AddCountryForm.vue')['default']
    AllCountries: typeof import('./src/components/AllCountries.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardImg: typeof import('bootstrap-vue-next')['BCardImg']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCarousel: typeof import('bootstrap-vue-next')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next')['BCarouselSlide']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BooksList: typeof import('./src/components/BooksList.vue')['default']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BucketList: typeof import('./src/components/BucketList.vue')['default']
    Carousel: typeof import('./src/components/HeaderCarousel.vue')['default']
    CountryDetails: typeof import('./src/components/GetCountry.vue')['default']
    CountryList: typeof import('./src/components/BucketList.vue')['default']
    FooterPart: typeof import('./src/components/FooterPart.vue')['default']
    GetCountry: typeof import('./src/components/GetCountry.vue')['default']
    HeaderCarousel: typeof import('./src/components/HeaderCarousel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ReviewCountryForm: typeof import('./src/components/ReviewCountryForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
  }
}
